---
driver:
  name: ec2
  region: eu-west-1
  require_chef_omnibus: true
  instance_type: t2.micro
  subnet_id: subnet-0e9b6138ff1ce18f2
  # subnet_id: subnet-0f608ae4045a016b2
  # security_group_ids: ["sg-0498d5bb99a76061d"]
  associate_public_ip: true
  aws-ssh-key-id: DevOpsStudents

provisioner:
  name: chef_solo

# transport:
#   ssh_key: ~/.ssh/DevOpsStudents.pem

verifier:
  name: inspec

platforms:
  - name: ubuntu-16.04
    driver:
      box: ubuntu/xenial64

suites:
  - name: default
    run_list:
      - recipe[node::default]
    verifier:
      inspec_tests:
        - test/integration/default
    attributes:
